# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-19 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('org', '培训机构'), ('per', '个人'), ('edu', '高校')], default='org', max_length=3, verbose_name='机构类型'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(max_length=200, upload_to='org/%Y/%m', verbose_name='机构logo'),
        ),
    ]
