# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-12 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180815_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userask',
            name='course_name',
            field=models.CharField(max_length=50, verbose_name='咨询课程'),
        ),
    ]
