# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-14 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_time',
            field=models.IntegerField(default=0, verbose_name='视频时长'),
        ),
    ]
