# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-14 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20180914_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_tell_you',
            field=models.TextField(default='', verbose_name='老师告诉你'),
        ),
        migrations.AddField(
            model_name='course',
            name='you_need_know',
            field=models.TextField(default='', verbose_name='课程须知'),
        ),
    ]
